# Generated by Django 5.2 on 2025-07-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='selected_avatar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
