# Generated by Django 5.2.4 on 2025-07-30 12:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("author", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Short summary of the blog post",
                        max_length=500,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Minimalist", "Minimalist"),
                            ("Vintage", "Vintage"),
                            ("Streetwear", "Streetwear"),
                            ("Bohemian", "Bohemian"),
                            ("Formal", "Formal"),
                            ("Casual", "Casual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="blog_covers/"),
                ),
                (
                    "cover_image_url",
                    models.URLField(
                        blank=True, help_text="Alternative to uploaded image", null=True
                    ),
                ),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("views_count", models.PositiveIntegerField(default=0)),
                (
                    "is_trending",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as trending to show in trending section",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Mark as featured for homepage display"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO title (max 60 characters)",
                        max_length=60,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="SEO description (max 160 characters)",
                        max_length=160,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
