# Generated by Django 5.2.4 on 2025-07-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
