# Generated by Django 5.2.4 on 2025-07-31 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_postcategory_trendinganalytics_trendingpost_postview_and_more'),
        ('api', '0007_alter_blog_published_at'),
    ]

    operations = [
    ]
