# Generated by Django 5.2 on 2025-07-31 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_blog_published_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designer_name', models.CharField(max_length=255)),
                ('designer_email', models.EmailField(max_length=254)),
                ('designer_phone', models.CharField(max_length=20)),
                ('design_title', models.CharField(max_length=255)),
                ('design_description', models.TextField()),
                ('category', models.CharField(choices=[('Apparel', 'Apparel'), ('Accessory', 'Accessory'), ('Footwear', 'Footwear'), ('Jewelry', 'Jewelry'), ('Other', 'Other')], max_length=20)),
                ('materials_used', models.CharField(max_length=500)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('portfolio_link', models.URLField(blank=True, null=True)),
                ('images', models.JSONField(default=list, help_text='List of image file paths')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin review')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Design Submission',
                'verbose_name_plural': 'Design Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
