# Generated by Django 5.2.4 on 2025-07-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20250731_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendingpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='postfavorite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postfavorite',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postfavorite',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postview',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postview',
            name='user',
        ),
        migrations.DeleteModel(
            name='TrendingAnalytics',
        ),
        migrations.RemoveField(
            model_name='trendingpost',
            name='author',
        ),
        migrations.AddField(
            model_name='blog',
            name='images',
            field=models.JSONField(blank=True, help_text='List of image URLs for the blog post', null=True),
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
        migrations.DeleteModel(
            name='PostFavorite',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
        migrations.DeleteModel(
            name='PostView',
        ),
        migrations.DeleteModel(
            name='TrendingPost',
        ),
    ]
