# Generated by Django 5.2.4 on 2025-08-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_designsubmission"),
        ("api", "0009_remove_trendingpost_category_and_more"),
    ]

    operations = []
