# Generated by Django 5.2.4 on 2025-08-02 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20250802_1257'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='images',
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('instagram_handle', models.CharField(blank=True, max_length=100)),
                ('personal_website', models.URLField(blank=True)),
                ('fashion_interest', models.CharField(blank=True, choices=[('Streetwear', 'Streetwear'), ('Vintage', 'Vintage'), ('Minimalist', 'Minimalist'), ('Bohemian', 'Bohemian'), ('Formal/Elegant', 'Formal/Elegant'), ('Casual', 'Casual'), ('Sustainable Fashion', 'Sustainable Fashion'), ('High Fashion', 'High Fashion'), ('Street Style', 'Street Style'), ('Other', 'Other')], max_length=50)),
                ('what_brings_you_here', models.CharField(blank=True, choices=[('Discover new styles', 'Discover new styles'), ('Connect with fashion community', 'Connect with fashion community'), ('Showcase my designs', 'Showcase my designs'), ('Learn about fashion trends', 'Learn about fashion trends'), ('Find inspiration', 'Find inspiration'), ('Network with students', 'Network with students'), ('Support student designers', 'Support student designers'), ('Other', 'Other')], max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('subscribe_newsletter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Member',
                'verbose_name_plural': 'Community Members',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DesignSubmission',
        ),
    ]
