# Generated by Django 5.2 on 2025-08-03 02:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_blog_images_communitymember_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lookbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('style_persona', models.CharField(choices=[('minimalist-style', 'Minimalist Style'), ('bohemian-style', 'Bohemian Style'), ('vintage-style', 'Vintage Style'), ('casual-style', 'Casual Style'), ('streetwear-style', 'Streetwear Style'), ('formal-style', 'Formal Style')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'style_persona')},
            },
        ),
        migrations.CreateModel(
            name='LookbookItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.lookbook')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'ordering': ['order', 'added_at'],
                'unique_together': {('lookbook', 'product')},
            },
        ),
    ]
