from django.core.management.base import BaseCommand
from api.models import Product
from decimal import Decimal

class Command(BaseCommand):
    help = 'Populate the database with products from the frontend data'

    def handle(self, *args, **options):
        # Product data from frontend/src/data/products.ts
        products_data = [
            # Minimalist Category Products
            {
                'name': "Classic White Button Down",
                'price': Decimal('45.00'),
                'description': "A timeless white button-down shirt crafted from premium cotton. Perfect for both professional and casual settings.",
                'image_url': "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400",
                'category': "Minimalist",
                'brand': "Emma Chen",
                'stock_quantity': 50,
            },
            {
                'name': "Tailored Black Trousers",
                'price': Decimal('60.00'),
                'description': "Perfectly tailored black trousers with a modern slim fit. Made from premium wool blend for comfort and durability.",
                'image_url': "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400",
                'category': "Minimalist",
                'brand': "Olivia White",
                'stock_quantity': 35,
            },
            {
                'name': "Cashmere Turtleneck",
                'price': Decimal('120.00'),
                'description': "Luxurious cashmere turtleneck in neutral tones. The perfect layering piece for sophisticated minimalist looks.",
                'image_url': "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400",
                'category': "Minimalist",
                'brand': "Olivia White",
                'stock_quantity': 25,
            },
            {
                'name': "Minimalist Linen Blazer",
                'price': Decimal('175.00'),
                'description': "A lightweight linen blazer in a soft sand color, perfect for layering over any minimalist outfit.",
                'image_url': "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=400",
                'category': "Minimalist",
                'brand': "Ethan White",
                'stock_quantity': 20,
            },
            {
                'name': "Structured Minimalist Tote",
                'price': Decimal('120.00'),
                'description': "A sleek, structured tote bag in vegan leather, perfect for everyday minimalist style.",
                'image_url': "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400",
                'category': "Minimalist",
                'brand': "Ava Lee",
                'stock_quantity': 30,
            },
            {
                'name': "Minimalist Slip Dress",
                'price': Decimal('135.00'),
                'description': "A simple slip dress in a soft matte satin, ideal for layering or wearing solo.",
                'image_url': "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400",
                'category': "Minimalist",
                'brand': "Ethan White",
                'stock_quantity': 28,
            },
            {
                'name': "Monochrome Crewneck Sweater",
                'price': Decimal('99.00'),
                'description': "A soft crewneck sweater in a monochrome palette, perfect for minimalist wardrobes.",
                'image_url': "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400",
                'category': "Minimalist",
                'brand': "Olivia White",
                'stock_quantity': 40,
            },
            {
                'name': "Minimalist Ribbed Tank Top",
                'price': Decimal('45.00'),
                'description': "A fitted ribbed tank in soft organic cotton, perfect for layering or wearing solo.",
                'image_url': "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=400",
                'category': "Minimalist",
                'brand': "Sophia Lin",
                'stock_quantity': 45,
            },
            {
                'name': "Minimalist Wide-Leg Pants",
                'price': Decimal('120.00'),
                'description': "High-waisted wide-leg pants in a neutral palette for a clean, modern look.",
                'image_url': "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400",
                'category': "Minimalist",
                'brand': "Ethan White",
                'stock_quantity': 32,
            },

            # Bohemian Category Products
            {
                'name': "Flowing Maxi Dress",
                'price': Decimal('55.00'),
                'description': "A beautiful flowing maxi dress with intricate embroidered details. Perfect for free-spirited fashion lovers.",
                'image_url': "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400",
                'category': "Bohemian",
                'brand': "Sophie Laurent",
                'stock_quantity': 38,
            },
            {
                'name': "Vintage Denim Jacket",
                'price': Decimal('35.00'),
                'description': "Authentic vintage-style denim jacket with distressed details and unique character.",
                'image_url': "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=400",
                'category': "Bohemian",
                'brand': "Sophie Laurent",
                'stock_quantity': 42,
            },
            {
                'name': "Crochet Cardigan",
                'price': Decimal('70.00'),
                'description': "Hand-crocheted cardigan with intricate patterns. A bohemian essential for layering.",
                'image_url': "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400",
                'category': "Bohemian",
                'brand': "Sophie Laurent",
                'stock_quantity': 25,
            },
            {
                'name': "Boho Fringe Kimono",
                'price': Decimal('100.00'),
                'description': "Lightweight kimono with fringe trim and a bold boho print. Perfect for layering over festival outfits.",
                'image_url': "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=400",
                'category': "Bohemian",
                'brand': "Maya Silva",
                'stock_quantity': 30,
            },
            {
                'name': "Patchwork Boho Skirt",
                'price': Decimal('55.00'),
                'description': "A midi skirt with patchwork prints and a flowy silhouette, perfect for bohemian style.",
                'image_url': "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400",
                'category': "Bohemian",
                'brand': "Lila Rose",
                'stock_quantity': 35,
            },
            {
                'name': "Embroidered Peasant Blouse",
                'price': Decimal('72.00'),
                'description': "A lightweight peasant blouse with colorful embroidery and tassel ties.",
                'image_url': "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=400",
                'category': "Bohemian",
                'brand': "Maya Silva",
                'stock_quantity': 28,
            },
            {
                'name': "Beaded Boho Sandals",
                'price': Decimal('65.00'),
                'description': "Flat sandals with beaded straps and a bohemian vibe, perfect for summer festivals.",
                'image_url': "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400",
                'category': "Bohemian",
                'brand': "Chloe Patel",
                'stock_quantity': 40,
            },
            {
                'name': "Bohemian Patchwork Kimono",
                'price': Decimal('105.00'),
                'description': "A lightweight kimono with patchwork prints and flowing sleeves, perfect for layering.",
                'image_url': "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=400",
                'category': "Bohemian",
                'brand': "Maya Silva",
                'stock_quantity': 22,
            },
            {
                'name': "Boho Tassel Earrings",
                'price': Decimal('29.00'),
                'description': "Handmade earrings with colorful tassels and beads for a free-spirited boho look.",
                'image_url': "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400",
                'category': "Bohemian",
                'brand': "Chloe Patel",
                'stock_quantity': 60,
            },

            # Vintage Category Products
            {
                'name': "Retro Polka Dot Dress",
                'price': Decimal('65.00'),
                'description': "A classic 1950s-inspired polka dot dress with a flattering fit-and-flare silhouette.",
                'image_url': "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400",
                'category': "Vintage",
                'brand': "Clara Rossi",
                'stock_quantity': 30,
            },
            {
                'name': "Vintage Leather Satchel",
                'price': Decimal('200.00'),
                'description': "Handcrafted leather satchel with brass hardware, inspired by 1970s vintage accessories.",
                'image_url': "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400",
                'category': "Vintage",
                'brand': "Grace Kelly",
                'stock_quantity': 15,
            },
            {
                'name': "Classic Tweed Blazer",
                'price': Decimal('185.00'),
                'description': "A timeless tweed blazer with a tailored fit, perfect for vintage-inspired office looks.",
                'image_url': "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=400",
                'category': "Vintage",
                'brand': "Ryan Green",
                'stock_quantity': 20,
            },
            {
                'name': "Vintage Pleated Skirt",
                'price': Decimal('95.00'),
                'description': "A midi-length pleated skirt in a retro floral print, inspired by 1970s fashion.",
                'image_url': "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400",
                'category': "Vintage",
                'brand': "Ella Brown",
                'stock_quantity': 25,
            },
            {
                'name': "Vintage Corduroy Overalls",
                'price': Decimal('130.00'),
                'description': "Classic corduroy overalls with adjustable straps and a retro fit.",
                'image_url': "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400",
                'category': "Vintage",
                'brand': "Mason Clark",
                'stock_quantity': 18,
            },
            {
                'name': "Retro Cat-Eye Sunglasses",
                'price': Decimal('49.00'),
                'description': "1950s-inspired cat-eye sunglasses with colored frames for a vintage look.",
                'image_url': "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400",
                'category': "Vintage",
                'brand': "Grace Kelly",
                'stock_quantity': 45,
            },
            {
                'name': "Vintage Argyle Sweater Vest",
                'price': Decimal('85.00'),
                'description': "A soft sweater vest with a classic argyle pattern, perfect for layering vintage outfits.",
                'image_url': "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400",
                'category': "Vintage",
                'brand': "Ella Brown",
                'stock_quantity': 22,
            },
            {
                'name': "Vintage Floral Midi Dress",
                'price': Decimal('110.00'),
                'description': "A 1970s-inspired midi dress with a bold floral print and puff sleeves.",
                'image_url': "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400",
                'category': "Vintage",
                'brand': "Clara Rossi",
                'stock_quantity': 28,
            },
            {
                'name': "Retro Varsity Jacket",
                'price': Decimal('150.00'),
                'description': "A classic varsity jacket with striped ribbing and chenille patches for a true vintage vibe.",
                'image_url': "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=400",
                'category': "Vintage",
                'brand': "Mason Clark",
                'stock_quantity': 20,
            },

            # Streetwear Category Products
            {
                'name': "Graphic Oversized Hoodie",
                'price': Decimal('30.00'),
                'description': "Comfortable oversized hoodie with bold graphics. Perfect for casual streetwear looks.",
                'image_url': "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400",
                'category': "Streetwear",
                'brand': "David Kim",
                'stock_quantity': 55,
            },
            {
                'name': "Distressed High-Waist Jeans",
                'price': Decimal('50.00'),
                'description': "Trendy high-waist jeans with distressed details. A streetwear essential for urban fashion lovers.",
                'image_url': "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400",
                'category': "Streetwear",
                'brand': "David Kim",
                'stock_quantity': 40,
            },
            {
                'name': "Chunky Platform Sneakers",
                'price': Decimal('120.00'),
                'description': "Bold platform sneakers with a chunky sole, perfect for making a statement in any streetwear outfit.",
                'image_url': "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400",
                'category': "Streetwear",
                'brand': "Jayden Park",
                'stock_quantity': 35,
            },
            {
                'name': "Street Art Graphic Tee",
                'price': Decimal('55.00'),
                'description': "Soft cotton t-shirt with a unique street art-inspired graphic print.",
                'image_url': "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=400",
                'category': "Streetwear",
                'brand': "Kenji Tanaka",
                'stock_quantity': 48,
            },
            {
                'name': "Cargo Pocket Joggers",
                'price': Decimal('110.00'),
                'description': "Relaxed-fit joggers with cargo pockets and elastic cuffs, a streetwear staple.",
                'image_url': "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400",
                'category': "Streetwear",
                'brand': "Liam Smith",
                'stock_quantity': 32,
            },
            {
                'name': "Streetwear Bucket Hat",
                'price': Decimal('39.00'),
                'description': "A reversible bucket hat with bold streetwear graphics and a relaxed fit.",
                'image_url': "https://images.unsplash.com/photo-1521369909029-2afed882baee?w=400",
                'category': "Streetwear",
                'brand': "Jayden Park",
                'stock_quantity': 50,
            },
            {
                'name': "Oversized Street Graphic Crewneck",
                'price': Decimal('89.00'),
                'description': "A heavyweight crewneck sweatshirt with a bold street graphic print.",
                'image_url': "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400",
                'category': "Streetwear",
                'brand': "Kenji Tanaka",
                'stock_quantity': 38,
            },
            {
                'name': "Streetwear Tech Cargo Shorts",
                'price': Decimal('75.00'),
                'description': "Utility cargo shorts with multiple pockets and a relaxed fit, perfect for summer street style.",
                'image_url': "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400",
                'category': "Streetwear",
                'brand': "Jayden Park",
                'stock_quantity': 25,
            },
            {
                'name': "Oversized Streetwear Flannel Shirt",
                'price': Decimal('69.00'),
                'description': "A soft, oversized flannel shirt with bold plaid patterns for a street-inspired look.",
                'image_url': "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=400",
                'category': "Streetwear",
                'brand': "Kenji Tanaka",
                'stock_quantity': 30,
            },

            # Formal Category Products
            {
                'name': "Black Silk Evening Dress",
                'price': Decimal('180.00'),
                'description': "Elegant black silk dress perfect for formal occasions. Features a sophisticated silhouette and premium fabric.",
                'image_url': "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400",
                'category': "Formal",
                'brand': "Alex Rivera",
                'stock_quantity': 20,
            },
            {
                'name': "Tailored Suit Set",
                'price': Decimal('250.00'),
                'description': "Professional suit set with blazer and matching trousers. Perfect for business meetings and formal events.",
                'image_url': "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=400",
                'category': "Formal",
                'brand': "Alex Rivera",
                'stock_quantity': 15,
            },
            {
                'name': "Embellished Evening Gown",
                'price': Decimal('340.00'),
                'description': "Floor-length evening gown with hand-sewn embellishments and a dramatic open back.",
                'image_url': "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400",
                'category': "Formal",
                'brand': "Benjamin Scott",
                'stock_quantity': 12,
            },
            {
                'name': "Classic Tuxedo Jacket",
                'price': Decimal('295.00'),
                'description': "A classic tuxedo jacket with satin lapels, perfect for black-tie events and formal occasions.",
                'image_url': "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=400",
                'category': "Formal",
                'brand': "Oliver Stone",
                'stock_quantity': 18,
            },
            {
                'name': "Silk Bow Tie",
                'price': Decimal('55.00'),
                'description': "A classic silk bow tie in elegant colors, perfect for formal occasions.",
                'image_url': "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400",
                'category': "Formal",
                'brand': "Oliver Stone",
                'stock_quantity': 35,
            },
            {
                'name': "Formal Patent Leather Loafers",
                'price': Decimal('160.00'),
                'description': "Shiny patent leather loafers with a classic silhouette for formal events.",
                'image_url': "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400",
                'category': "Formal",
                'brand': "Benjamin Scott",
                'stock_quantity': 25,
            },
            {
                'name': "Embroidered Formal Pocket Square",
                'price': Decimal('35.00'),
                'description': "A silk pocket square with subtle embroidery, the perfect finishing touch for a formal suit.",
                'image_url': "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400",
                'category': "Formal",
                'brand': "Alex Rivera",
                'stock_quantity': 45,
            },
            {
                'name': "Formal Velvet Blazer",
                'price': Decimal('210.00'),
                'description': "A luxurious velvet blazer with a tailored fit, perfect for formal events and parties.",
                'image_url': "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=400",
                'category': "Formal",
                'brand': "Benjamin Scott",
                'stock_quantity': 16,
            },
            {
                'name': "Embroidered Formal Maxi Dress",
                'price': Decimal('340.00'),
                'description': "A floor-length formal dress with intricate embroidery and a flowing silhouette.",
                'image_url': "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400",
                'category': "Formal",
                'brand': "Olivia Turner",
                'stock_quantity': 10,
            },

            # Casual Category Products
            {
                'name': "Relaxed Fit Crew Tee",
                'price': Decimal('22.00'),
                'description': "A soft, relaxed fit crew neck t-shirt in breathable cotton. Perfect for everyday casual wear.",
                'image_url': "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=400",
                'category': "Casual",
                'brand': "Emma Chen",
                'stock_quantity': 80,
            },
            {
                'name': "Classic Blue Jeans",
                'price': Decimal('35.00'),
                'description': "Timeless straight-leg blue jeans with a comfortable mid-rise fit.",
                'image_url': "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400",
                'category': "Casual",
                'brand': "Noah Kim",
                'stock_quantity': 65,
            },
            {
                'name': "Everyday Canvas Sneakers",
                'price': Decimal('65.00'),
                'description': "Low-top canvas sneakers with a cushioned insole for all-day comfort.",
                'image_url': "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400",
                'category': "Casual",
                'brand': "Ava Lee",
                'stock_quantity': 55,
            },
            {
                'name': "Lightweight Zip Hoodie",
                'price': Decimal('59.00'),
                'description': "A lightweight zip-up hoodie in soft French terry, ideal for layering on cool days.",
                'image_url': "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400",
                'category': "Casual",
                'brand': "Lila Rose",
                'stock_quantity': 45,
            },
            {
                'name': "Casual Henley Shirt",
                'price': Decimal('49.00'),
                'description': "A classic long-sleeve Henley shirt in soft jersey, perfect for layering or wearing alone.",
                'image_url': "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=400",
                'category': "Casual",
                'brand': "Noah Kim",
                'stock_quantity': 38,
            },
            {
                'name': "Casual Drawstring Shorts",
                'price': Decimal('55.00'),
                'description': "Lightweight drawstring shorts in breathable cotton, ideal for warm weather.",
                'image_url': "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400",
                'category': "Casual",
                'brand': "Ava Lee",
                'stock_quantity': 42,
            },
        ]

        # Clear existing products
        Product.objects.all().delete()
        self.stdout.write(self.style.SUCCESS('Cleared existing products'))

        # Create products
        created_count = 0
        for product_data in products_data:
            product, created = Product.objects.get_or_create(
                name=product_data['name'],
                defaults=product_data
            )
            if created:
                created_count += 1

        self.stdout.write(
            self.style.SUCCESS(f'Successfully created {created_count} products')
        ) 